= Rendering Test

asciidoc source from link:http://asciidoc.org/[asciidoc.org]

* 1111111111
* 1111111111
** 2222222222
** 2222222222
* 1111111111
* 1111111111
** 2222222222
** 2222222222
** 2222222222
*** 3333333333
*** 3333333333
*** 3333333333
*** 3333333333
** 2222222222
** 2222222222

== Macros

=== image_grid

image_grid::begin[]

.image_cell_1
image_cell::/images/plant/2019-08-27/p8273777[]
.image_cell_2
image_cell::/images/plant/2019-08-27/p8273778[]


image_grid::end[]

== class attributes

hoge hoge [.hoge]#hoge hoge#.


== List continuation

* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----


== CSS 

== h2

=== h3
 
==== h4


== Math Formulae

=== LaTeXMathML (MathJax)

http://www.maths.nottingham.ac.uk/personal/drw/lm.html[LaTeXMathML]
capability has been added to AsciiDoc for users who are more familar
with or prefer LaTeX math formulas to the
http://asciidoc.org/asciimathml.html[ASCIIMathML]
notation.

'LaTeXMathML' is a derivative of
http://asciidoc.org/asciimathml.html[ASCIIMathML] -- in
terms of usage the only difference it that you use the `latexmath`
attribute instead of the `asciimath` attribute.

'LaTeXMathML' processes LaTeX math formulas not arbitrary LaTeX (as
`dblatex(1)` does). See the
http://www.maths.nottingham.ac.uk/personal/drw/lm.html[LaTeXMathML]
website for details.

Here's the link:latexmathml.txt[AsciiDoc source] that generated this
page.

Some example 'LaTeXMathML' formulas:


[latexmath]
++++
R_x = 10.0 \times \sin(R_\phi)
++++



== Syntax Highlighting

=== Source code paragraphs

[source,python]
if n < 0: print 'Hello World!'

:language: python

[source]
if n < 0: print 'Hello World!'

[source,ruby,numbered]
[true, false].cycle([0, 1, 2, 3, 4]) do |a, b|
    puts "#{a.inspect} => #{b.inspect}"


=== Unnumbered source code listing

[source,python]
---------------------------------------------------------------------
''' A multi-line
    comment.'''
def sub_word(mo):
    ''' Single line comment.'''
    word = mo.group('word')   # Inline comment
    if word in keywords[language]:
        return quote + word + quote
    else:
        return word
---------------------------------------------------------------------

comment def sub_word

word mo.group() if word in keywords

本日は晴天なり．


=== Numbered source code listing with callouts

[source,ruby,numbered]
---------------------------------------------------------------------
#
# Useful Ruby base class extensions.
#

class Array

  # Execute a block passing it corresponding items in
  # +self+ and +other_array+.
  # If self has less items than other_array it is repeated.

  def cycle(other_array)  # :yields: item, other_item
    other_array.each_with_index do |item, index|
      yield(self[index % self.length], item)
    end
  end

end

if $0 == __FILE__                                 # <1>
  # Array#cycle test
  # true => 0
  # false => 1
  # true => 2
  # false => 3
  # true => 4
  puts 'Array#cycle test'                         # <2>
  [true, false].cycle([0, 1, 2, 3, 4]) do |a, b|
    puts "#{a.inspect} => #{b.inspect}"
  end
end
---------------------------------------------------------------------

<1> First callout.
<2> Second callout.
