:figure-caption!:

= フウセンカズラ栽培日記

某工大すずかけ台キャンパスで [line-through]*違法* 合法(2019-08-06に合法になりました)栽培しているフウセンカズラの栽培日記．

* ビバ号
** スーパービバホームで180円ほどで購入した株．
* 大岡山1号
** 大岡山の某所より違法採取された種から一番初めに発芽した株．
* 大岡山2号
** 大岡山1号とは時を異にして発芽した株．

大岡山の某所で入手したフウセンカズラの種を蒔いたがなかなか発芽せず，寂しくなったのでビバホームで苗を購入．
その後，種が発芽(1号, 2号)したためにいろいろな株がある．


== 2019-08-26(月) 16:00

晴れ．雷．

再び1号に実がついた．

昼下がりに夕立が来たが，雨はさほど降らなかったため水やりをした．

土日に水やりをしなかったが，皆元気であった．
2号が少し倒れ気味だったのでフェンスに巻きつけておいた．

image_grid::begin[]

.全体の様子
image_cell::/plant/2019-08-26/p8263767[]

.全体の根本部分
image_cell::/plant/2019-08-26/p8263771[]

.全体の成長具合．土日でかなり変化した．
image_cell::/plant/2019-08-26/p8263772[]

.ビバ号最前線
image_cell::/plant/2019-08-26/p8263768[]

.1号最前線
image_cell::/plant/2019-08-26/p8263769[]

.1号の実その1
image_cell::/plant/2019-08-26/p8263775[]

.1号の実その2
image_cell::/plant/2019-08-26/p8263776[]

.1号の花．ピンぼけだが立派な花が一つ咲いていた．
image_cell::/plant/2019-08-26/p8263774[]

.2号最前線
image_cell::/plant/2019-08-26/p8263770[]

.2号のつぼみたち
image_cell::/plant/2019-08-26/p8263773[]

image_grid::end[]

== 2019-08-23 12:00

雨．

雨が降っていたので水やりは行わなかった．

すこぶる順調である．
周りの草たちも再び勢力を伸ばしつつある．

image_grid::begin[]

.全体の様子
image_cell::/plant/2019-08-23/p8233757[]

.全体の根本部分
image_cell::/plant/2019-08-23/p8233761[]

.全体の成長具合．近頃やはり成長速度がはやい，
image_cell::/plant/2019-08-23/p8233762[]

.ビバ号最前線
image_cell::/plant/2019-08-23/p8233758[]

.1号最前線
image_cell::/plant/2019-08-23/p8233759[]

.1号の花．今日は割と咲いていた．午前中に多く咲いているのかもしれない．
image_cell::/plant/2019-08-23/p8233764[]

.1号の脇芽の巻きひげがフェンスをとらえた様子．
image_cell::/plant/2019-08-23/p8233765[]

.2号最前線
image_cell::/plant/2019-08-23/p8233760[]

.2号につぼみがついた様子．画像中央の最前線をよく観るとつぼみが見える．
image_cell::/plant/2019-08-23/p8233766[]

image_grid::end[]

== 2019-08-22 15:00

くもり．時々晴れ．

今日は割と涼しい日である．
10:00ごろに水やりをし，午後観察をした．

フウセンカズラ達は相変わらず元気で，昨日と比べてわかるほど成長しており驚いた．
ビバ号・1号に関しては脇芽が大量に見受けられ，お盆危機後の大成長時代である．

image_grid::begin[]

.全体の様子
image_cell::/plant/2019-08-22/p8223748[]

.全体の根元部分
image_cell::/plant/2019-08-22/p8223751[]

.全体の成長具合．どのくらい伸びたかわかるように，今後このような写真を載せていこうと思う．
image_cell::/plant/2019-08-22/p8223755[]

.ビバ号最前線
image_cell::/plant/2019-08-22/p8223749[]

.1号最前線
image_cell::/plant/2019-08-22/p8223750[]

.1号の花．今日はあまり花が咲いていなかった．
image_cell::/plant/2019-08-22/p8223753[]

.2号最前線
image_cell::/plant/2019-08-22/p8223752[]

image_grid::end[]

相変わらず実は確認できず．

== 2019-08-21

晴れ．くもり．

バスケットボールコートでテニスの壁打ちをしている人がいた．

全体的に良好だがなかなか実ができない．
先日実ができたが一日で消えてしまった．

image_grid::begin[]

.全体の様子
image_cell::/plant/2019-08-21/p8213741[]

.全体の根元部分
image_cell::/plant/2019-08-21/p8213745[]

.ビバ号最前線
image_cell::/plant/2019-08-21/p8213744[]

.1号最前線
image_cell::/plant/2019-08-21/p8213742[]

.1号の下の部分．途中から脇芽が出てきて元気な様子．
image_cell::/plant/2019-08-21/p8213746[]

.1号の花．昨日と様子が違う．花の様子は毎日違う気がする．
image_cell::/plant/2019-08-21/p8213747[]

.2号最前線．1日経っただけでも葉っぱが大きくなっていたりと，成長を確認できる．
image_cell::/plant/2019-08-21/p8213740[]

.昨日の2号最前線．
image_cell::/plant/2019-08-20/p8203738[]

image_grid::end[]

== 2019-08-20

晴れ．

お盆に実家に行っていたため1週間放置．
その間に台風が来たので，水に関してはなんとかしのいだ様子だったが，鉢植えのまま放置した2号は風で倒れてしまっていた．そのため2号はかなり萎れた状態だったが，昨晩の水やりと夕立でなんとか回復した模様．

全体的に最前線は良好で，健康的な葉をしている．

image_grid::begin[]

.全体の様子
image_cell::/plant/2019-08-20/p8203735[]

.ビバ号最前線
image_cell::/plant/2019-08-20/p8203736[]

.1号最前線．風で少し茎が折れ気味だったので，フェンスに絡ませておいた．
image_cell::/plant/2019-08-20/p8203737[]

.1号の花．
image_cell::/plant/2019-08-20/p8203739[]

.2号最前線．昨日はかなり萎れていたが，ここまで回復した．
image_cell::/plant/2019-08-20/p8203738[]

image_grid::end[]

== 2019-08-08

晴れ．

今日はクローズアップレンズとともに撮影に向かう．

image_grid::begin[]

.ビバ号．虫がちゃんと花にたかっている．フウセンカズラは自家受粉らしく，花をつつくだけで受粉が完了するかもしれない．
image_cell::/plant/2019-08-08/p8083643[]

.ビバ号最前線．数日前に先端がやられてしまったが，そのおかげ?で横からたくさん芽がでてきてよく茂るようになった気がする．上の方は結構花が咲いている．
image_cell::/plant/2019-08-08/p8083646[]

.ビバ号の花
image_cell::/plant/2019-08-08/p8083645[]

.大岡山1号．ついに実がついた!
image_cell::/plant/2019-08-08/p8083648[]

.大岡山1号の最前線．大岡山1号はあまり花が咲いていない．葉っぱも色が薄いし少し心配ではある．しかし，大岡山1・2号のオリジナルは大岡山で健在であることが本日確認された．
image_cell::/plant/2019-08-08/p8083642[]

.大岡山2号の最前線．必死にフェンスにしがみついている，
image_cell::/plant/2019-08-08/p8083640[]

image_grid::end[]


== 2019-08-06

晴れ．

なんと家の室内の植木の鉢から大岡山2号が．(昨日は気づかなかった)
急遽植え替えすることに．

image_grid::begin[]
image_cell::/plant/2019-08-06/p8063615[]
image_grid::end[]

この日は大学のフウセンカズラ戦線の土の入れ替えをした．
土を加藤山から拝借し，いざフウセンカズラのもとに向かうと，草刈り部隊が!

しかも昨日の所業のせいで，落ち葉が大変なことに!

image_grid::begin[]
image_cell::/plant/2019-08-06/p8063617[]
image_cell::/plant/2019-08-06/p8063616[]
image_grid::end[]

草刈り部隊にバレぬよう土を掘り返していると，「なにしてるの」とあっけなくばれる．
怒られると思いきや，結構おもしろく思っていただけたらしく，最終的には良い土の場所を教えてくれるまで話が進んだ．

土を補充しに教えてくれた所にむかう．
わざわざ草刈りを止めてもらったりもした．(荒らしてしまってすみません...)
半袖半ズボンだったので，ハチに注意するよう親切に注意までしていただいた．




== 2019-08-05

晴れ．日がかげるときもあるが暑い．

フウセンカズラたちが蔦の影になっていたので，実家から持ってきた剪定ばさみでフェンスにかかった蔦の葉を落とすことにした．
それと，周りの草も多少刈った．

ついでに蔦の幹を全部切断しておいた．次の日までに上も全滅だろう．

image_grid::begin[]

image_cell::/plant/2019-08-05/p8053600[]

.before
image_cell::/plant/2019-08-05/p8053599[]

.after
image_cell::/plant/2019-08-05/p8053606[]

.大岡山1号の最前線
image_cell::/plant/2019-08-05/p8053608[]

.大岡山1号の右側の花
image_cell::/plant/2019-08-05/p8053610[]

.ビバ号の最前線
image_cell::/plant/2019-08-05/p8053612[]

image_grid::end[]


== 2019-07-12

雨

image_grid::begin[]

.室内時代のビバ号
image_cell::/plant/2019-07-12/p7123553[]

image_grid::end[]

