= 線形代数

線形代数ができなくてやばすぎるので復習しています．余裕があれば証明も載せたいです．
主に「教養の線形代数」(培風館)を参考にしています．

== 行列 matrix
// {{{

\[
A = 
\begin{bmatrix}
a_{1, 1} & a_{1, 2} & \cdots & a_{1, n} \\
a_{2, 1} & a_{2, 2} & \cdots & a_{2, n} \\
\vdots   & \vdots   & \ddots & \vdots   \\
a_{m, 1} & a_{m, 2} & \cdots & a_{m, n} \\
\end{bmatrix}
\]

と書いたものを， \( m \times n \) 行列という．

上から \(i\) 番目の行を第 \(i\) 行(row)，左から \(j\) 番目の列を第 \(j\) 列(column)という．

\(A\) の \((i, j)\) 成分(entry)は \(a_{i, j}\) である．

=== 転置行列 transpose matrix

\[
\newcommand{\tr}[1]{{}^t\!#1}
\tr{A} = A^{\mathrm{T}} =
\begin{bmatrix}
a_{1, 1} & a_{2, 1} & \cdots & a_{m, 1} \\
a_{1, 2} & a_{2, 2} & \cdots & a_{m, 2} \\
\vdots   & \vdots   & \ddots & \vdots   \\
a_{1, n} & a_{2, n} & \cdots & a_{m, n} \\
\end{bmatrix}
\]

==== 転置行列の性質

[latexmath]
++++
\newcommand{\inv}[1]{#1^{-1}}
\tr{(\tr{A})} = A \\
\tr{(A+B)} = \tr{A} + \tr{B} \\ 
\tr{(cA)} = c\tr{A} \\
\tr{(AB)} = \tr{B}\tr{A}
++++

=== 正則行列，逆行列

\(n\) 次正方行列 \(A\) に対して，

\[
AB = BA = I
\]

なる \(B\) が存在するとき，\(A\) は **正則行列** ，あるいは **正則** であると言う．このとき， \(B\) は \(A\) に対して一意に定まり，この \(B\) を \(\inv{A}\) と表し，\(A\) の **逆行列** という．

\[
A\inv{A} = \inv{A}A = I
\]

==== 正則性の判定

\(A\) を \(n\) 次正方行列とすると，次の4つは同値である．

[latexmath]
++++
A が正則 \\
\mathrm{rank} A=n \\
A の階段行列が単位行列 I_n \\
|A| \neq 0
++++

==== 逆行列の性質

\(A\)，\(B\) が正則であれば， \(\inv{A}\)，\(AB\)，\(\tr{A}\) はいずれも正則で，

[latexmath]
++++
\inv{(\inv{A})} = A \\
\inv{AB} = \inv{B}\inv{A} \\
\inv{(\tr{A})} = \tr{(\inv{A})}
++++

=== ユニモジュラ行列

各要素が整数で行列式が \(+1\) あるいは \(-1\) の行列をユニモジュラ行列という．

==== 性質

\(b\) を全ての要素が整数のベクトルとするとき， \(Mx=b\) には整数解が存在する．

//=== エルミート行列

//=== ユニタリ行列

//=== 正規行列

=== 対角和

\[
\mathrm{Tr} A = \sum_{i=1}^{n} a_{i, i}
\]

// }}}

== 連立一次方程式 system of linear equations
// {{{

=== 階数

行列 \(A\) の階段行列における零ベクトルでない行の数 \(k\) を **階数** と言い， \(\newcommand{\rank}[0]{\mathrm{rank}}\rank A\) で表す．

==== 階数の性質

\(P\)，\(Q\) を正則行列とする．

[latexmath]
++++
\rank(PA) = \rank A \\
\rank(AQ) = \rank A \\
\rank(PAQ) = \rank A \\
\rank\tr{A} = \rank A
++++


=== 連立一次方程式の解

連立一次方程式 \(\newcommand{\bold}[1]{\boldsymbol{#1}} A\bold{x}=\bold{b}\) が解を持つための必要十分条件は，

\[
\rank[A, \bold{b}]=\rank A
\]

が成り立つこと．

_どんなときこれが成り立たないの?_

=== 連立方程式の解の自由度

未知数 \(n\) の連立一次方程式 \(A\bold{x}=\bold{b}\) が解を持つとき，ただ1組の解を持つための必要十分条件は
\(\rank A = n\)
であり，無数の解を持つための必要十分条件は，
\(\rank A < n\)
である．

無数の解を持つ時の解の自由度は \(n-\rank A\) である．実際に解を求めるときには，「段の1の無い列」に対応する未知数を全て任意定数とおくと良い．(これがよくわからん)

// }}}

== 行列式 determinant
// {{{

=== 定義

行列式は正方行列に対して定義される．

[latexmath]
++++
\det (A) = |A| = \sum_{\sigma \in S_n} \left( \mathrm{sgn} (\sigma)\prod_{i=1}^{n} a_{i, \sigma_i}\right)
++++

実際に行列式を求めるときは定義通りには計算せず，行列式の性質をうまく利用して求める．

=== 行列式の性質

==== 多重線形性

[latexmath]
++++
\left|\begin{array}{cccc}
\vdots                 & \vdots                 & \cdots & \vdots \\
b_{i, 1}+c_{i, 1} & b_{i, 2}+c_{i, 2} & \cdots & b_{i, n}+c_{i, n} \\
\vdots                 & \vdots                 & \cdots & \vdots \\
\end{array}\right|
=
\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
b_{i, 1} & b_{i, 2} & \cdots & b_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
+
\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
c_{i, 1} & c_{i, 2} & \cdots & c_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
\\

\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
cb_{i, 1} & cb_{i, 2} & \cdots & cb_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
=
c
\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
b_{i, 1} & b_{i, 2} & \cdots & b_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
++++

「多重」とは，どの行においても上の2つが成り立つということ．

==== 交代性

[latexmath]
++++
\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
a_{i, 1} & a_{i, 2} & \cdots & a_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
a_{j, 1} & a_{j, 2} & \cdots & a_{j, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
=
-
\left|\begin{array}{cccc}
\vdots        & \vdots        & \cdots & \vdots \\
a_{j, 1} & a_{j, 2} & \cdots & a_{j, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
a_{i, 1} & a_{i, 2} & \cdots & a_{i, n} \\
\vdots        & \vdots        & \cdots & \vdots \\
\end{array}\right|
++++

行を入れ替えると符号が変わる．

==== 値が0になる行列式

2つの行が比例している場合は，行列式の値が0になる．これの特殊な場合として「ある行が零ベクトル」がある．

==== 次数を下げる

[latexmath]
++++
\left|\begin{array}{cccc}
a_{1, 1} & a_{1, 2} & \cdots & a_{1, n} \\
0        & a_{2, 2} & \cdots & a_{2, n} \\
0        & \vdots   & \ddots & \vdots   \\
0        & a_{n, 2} & \cdots & a_{n, n} \\
\end{array}\right|
=
a_{1, 1}
\left|\begin{array}{ccc}
a_{2, 2} & \cdots & a_{2, n} \\
\vdots   & \ddots & \vdots   \\
a_{n, 2} & \cdots & a_{n, n} \\
\end{array}\right|
++++

これは行列式の定義を考えるとわかる．

**以上の性質は列に対しても同様である．**

==== その他の性質

\(A\)，\(B\) を同じ次数の正方行列とするとき，

[latexmath]
++++
|AB| = |A||B| \\
|\tr{A}| = |A|
++++
が成り立つ．

=== 行列式の図形的意味

行列式は各列ベクトルからなる平行多面体の符号付(半時計回り，右手系が正)体積になる．

// }}}

== (実)ベクトル空間 vector space

以下の集合 \(\mathbb{R}^n\) に，加法とスカラー倍の演算を導入するとき， \(\mathbb{R}^n\) を実数上の **\(n\) 次元数ベクトル空間** と言う．

[latexmath]
++++
\mathbb{R}^n = \left\{
\left.
\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n \\
\end{bmatrix}
\right|
x_1, x_2, \cdots, x_n \in \mathbb{R}
\right\}
++++

=== 1次(線形)独立・1次(線形)従属

ベクトル \(\bold{a}_1, \bold{a}_2, \cdots, \bold{a}_r\ \in \mathbb{R}^n\) が非自明な1次関係式を持たない時，ベクトルの組 \(\{\bold{a}_1, \bold{a}_2, \cdots, \bold{a}_r\}\) は **1次独立** であるという．1次独立でない時， **1次従属** という．

\(\mathbb{R}^n\) の \(n\) 個のベクトルの組に対しては， \(A=[\bold{a}_1, \bold{a}_2, \cdots, \bold{a}_n]\) の行列式で1次独立性を判定できる(非零の時に1次独立).

=== 部分空間

\(\mathbb{R}^n\) の部分集合 \(W\) が以下を満たすとき， \(W\) を \(\mathbb{R}^n\) の部分空間という．

[latexmath]
++++
\bold{0} \in W \\
\bold{a}, \bold{b} \in W \Longrightarrow \bold{a}+\bold{b} \in W \\
\bold{a} \in W, k \in \mathbb{R} \Longrightarrow k\bold{a} \in W \\
++++
