= Patchy Particles シミュレーションの流れ
:description: Patchy Particles を用いたモンテカルロシミュレーションの方法です．

arXivにある論文 https://arxiv.org/pdf/1802.04980.pdf で実装されているプログラムを解読します． +
ソースコードは https://zenodo.org/record/1171695#.XfpEkdmRVhE に公開されています．

== 概要

Patchy Particles とは，
粒子の排除効果以外に，
粒子の表面に配置されたパッチと呼ばれる小さな球領域を介して，
他の粒子と相互作用をする系です．

== 粒子の移動

=== `main`

`main.c` を見てみます． +
メインループの中で `syst.do_ensemble` が呼ばれています． +
`syst` はこのシミュレーションのコンテキストで，粒子や物理量パラメータなどが保持されています．


[source, c]
.main.c
----
// ...
int main(int argc, char *argv[]) {
    // ... (initialize)
    /**
     * Main loop
     */
    for(curr_step = output_files.start_from; curr_step < steps && !stop; curr_step++) {
        // ...
        /**
         * Perform a Monte Carlo sweep
         */
        syst.do_ensemble(&syst, &output_files);
    }
    // ...
}
----

=== `do_ensemble`

`syst.do_ensemble` は `MC.c` の `MC_init` 関数で初期化されます． +
いくつかの `ensemble` が用意されていて，ここでは `NVT` が選択されていると仮定します．

[source, c]
.MC.c
----
// ...
void MC_init(input_file *input, System *syst, Output *IO) {
    /**
     * Here we set the pointer to the function that will be used to make a Monte Carlo step
     * according to the ensemble specified in the input file
     */
    switch(syst->ensemble) {
    case NVT:
        syst->do_ensemble = &do_NVT;
        break;
    case GC:
        syst->do_ensemble = &do_GC;
        break;
    case SUS:
        syst->do_ensemble = &do_SUS;
        break;
    default:
        output_exit(IO, "Ensemble %d not supported\n", syst->ensemble);
        break;
    }
    // ...
}
// ...
----

=== `do_NVT`

`do_NVT` は次のように定義されています． +
至ってシンプルで， `N` 回 `do_dynamics` を実行します．

[source, c]
.MC.c
----
// ...
void do_NVT(System *syst, Output *output_files) {
    int i;
    for(i = 0; i < syst->N; i++) {
        syst->do_dynamics(syst, output_files);
    }
}
// ...
----

=== `do_dynamics`

`do_dynamics` は先程の `do_ensemble` と同じように `MC_init` 関数の中で初期化されています． +
今回は `MC_move_rototranslate` に設定されていると仮定します． +
これは論文中にもあるように，粒子に並進と回転を作用させるという選択です．

[source, c]
.MC.c
----
// ...
void MC_init(input_file *input, System *syst, Output *IO) {
    // ...
    /**
     * Here we set the pointer to the function that will be used to perform the type of dynamics
     * specified in the input file
     */
    switch(syst->dynamics) {
    case RTMC:
        syst->do_dynamics = &MC_move_rototranslate;
        break;
    case VMMC:
        VMMC_init(input, syst, IO);
        syst->do_dynamics = &VMMC_dynamics;
        break;
    case AVBMC:
        AVBMC_init(input, syst, IO);
        syst->do_dynamics = &AVBMC_dynamics;
        break;
    default:
        output_exit(IO, "Dynamics %d not supported\n", syst->dynamics);
        break;
    }
}
// ...
----

=== `MC_move_rototranslate`

この関数では，まず `N` 個ある粒子のうち1つをランダムに選びます(`*p`)． +

[source, c]
.MC.c
----
// ...
void MC_move_rototranslate(System *syst, Output *IO) {
    PatchyParticle *p = syst->particles + (int) (drand48() * syst->N);
    int type = ROTO_TRASL;
    syst->tries[type]++;

    vector disp;
    disp[0] = (drand48() - 0.5) * syst->disp_max;
    disp[1] = (drand48() - 0.5) * syst->disp_max;
    disp[2] = (drand48() - 0.5) * syst->disp_max;
    // new orientation
    double theta = drand48() * syst->theta_max;
    vector axis;
    matrix new_orient;
    random_vector_on_sphere(axis);
    utils_rotate_matrix(p->orientation, new_orient, axis, theta);

    // apply changes to p
    double deltaE = -MC_energy(syst, p);
    MC_rototraslate_particle(syst, p, disp, new_orient);
    deltaE += MC_energy(syst, p);

    if(!syst->overlap && (deltaE < 0. || drand48() < exp(-deltaE / syst->T))) {
        syst->energy += deltaE;
        syst->accepted[type]++;
    }
    else {
        MC_rollback_particle(syst, p);
        syst->overlap = 0;
    }
}
// ...
----

==== `disp`

`disp` は並進の移動量で，
xyz軸それぞれに `-0.5*syst->disp_max` から `+0.5*syst->disp_max` の範囲の一様ランダムな量が指定されます．

==== `theta`

`theta` は回転の量です． `0` から `syst->theta_max` の正の値をとります． +
(正の値でいいのは，回転軸は真逆の方向を向く場合もあるからです．)

==== `axis`

`axis` は回転軸です． +
`random_vector_on_sphere(axis)` で球面上のランダムな点を選び，それを回転軸としています． +
この軸回りに `theta` だけ粒子が回転することになります．

==== `new_orient`

`new_orient` は `theta` と `axis` の情報を元に合成された回転行列が格納されています． +
`p->orientation` には，今までその粒子に適用されてきた回転行列が記録されています． +
`util_rotate_matrix` によって今回の回転行列が加えられます．


以上の準備ができたら， `MC_rototraslate_particle` が呼ばれ，実際に粒子が並進・回転させられます．
(この中身は次で説明します) +
その前後で `p` 周りのエネルギーの変化が計算され `deltaE` に記録されます． +

その結果， `if` 文の箇所で，その移動が受理されるか却下されるかが決定されます． +
却下された場合は， `MC_rollback_particle` で元に戻されます．


=== `MC_rototraslate_particle`

ここでは `disp`, `orient` を元に，実際に粒子が並進・回転されます． +
同時に，粒子のもつパッチも回転されます． +
(このプログラムでは行列は3x3の2次元配列で表現されています．)

[source, cpp]
.MC.c
----
// ...
void MC_rototraslate_particle(System *syst, PatchyParticle *p, vector disp, vector *orient) {
    p->r_old[0] = p->r[0];
    p->r_old[1] = p->r[1];
    p->r_old[2] = p->r[2];

    p->r[0] += disp[0];
    p->r[1] += disp[1];
    p->r[2] += disp[2];

    int i, j;
    for(i = 0; i < 3; i++) {
        for(j = 0; j < 3; j++) {
            p->orientation_old[i][j] = p->orientation[i][j];
            p->orientation[i][j] = orient[i][j];
        }
    }

    for(i = 0; i < p->n_patches; i++) {
        MATRIX_VECTOR_MULTIPLICATION(p->orientation, p->base_patches[i], p->patches[i]);
    }

    MC_change_cell(syst, p);
}
// ...
----


== ポテンシャルの計算

ここでは，ある粒子とその他全ての粒子の間のエネルギーを計算します． +
ここは少しむずかしい．論文と一緒に追っていきたい．

=== `MC_energy`

この関数は，ある点にいくつのパッチがくっつきうるかを返します．

[source, c]
.MC.c
----
// ...
double MC_energy(System *syst, PatchyParticle *p) {
    syst->overlap = 0;
    double E = 0.;

    int ind[3], loop_ind[3];
    cells_fill_and_get_idx_from_particle(syst, p, ind);

    int j, k, l, p_patch, q_patch;

    for(j = -1; j < 2; j++) {
        loop_ind[0] = (ind[0] + j + syst->cells->N_side[0]) % syst->cells->N_side[0];
        for(k = -1; k < 2; k++) {
            loop_ind[1] = (ind[1] + k + syst->cells->N_side[1]) % syst->cells->N_side[1];
            for(l = -1; l < 2; l++) {
                loop_ind[2] = (ind[2] + l + syst->cells->N_side[2]) % syst->cells->N_side[2];
                int loop_index = (loop_ind[0] * syst->cells->N_side[1] + loop_ind[1]) * syst->cells->N_side[2] + loop_ind[2];

                PatchyParticle *q = syst->cells->heads[loop_index];
                while(q != NULL) {
                    if(q->index != p->index) {
                        int val = MC_interact(syst, p, q, &p_patch, &q_patch);

                        if(val == PATCH_BOND) {
                            E -= 1.;
                        }
                        else if(val == OVERLAP) {
                            syst->overlap = 1;
                            return 0.;
                        }
                    }
                    q = syst->cells->next[q->index];
                }
            }
        }
    }

    return E;
}
// ...
----

=== `MC_interact`

この関数は，点 `p` と点 `q` が相互作用するかどうかを返し，そのペアも `onp`, `onq` に格納されます．

[source, c]
.MC.c
----
// ...
inline int MC_interact(System *syst, PatchyParticle *p, PatchyParticle *q, int *onp, int *onq) {
    return MC_would_interact(syst, p, q->r, q->patches, onp, onq);
}
// ...
----

=== `MC_would_interact`

論文中にあるKern-Frenelの相互作用を計算します． +
お互いのパッチ同士の2重ループが見えます． +
おそらく初めて出会ったパッチ同士が接続されます．

[source, c]
.MC.c
----
// ...
int MC_would_interact(System *syst, PatchyParticle *p, vector r, vector *patches, int *onp, int *onq) {
    vector dist = {r[0] - p->r[0], r[1] - p->r[1], r[2] - p->r[2]};
    dist[0] -= syst->box[0] * rint(dist[0] / syst->box[0]);
    dist[1] -= syst->box[1] * rint(dist[1] / syst->box[1]);
    dist[2] -= syst->box[2] * rint(dist[2] / syst->box[2]);

    double dist2 = SCALAR(dist, dist);

    if(dist2 < 1.) return OVERLAP;
    else if(dist2 < syst->kf_sqr_rcut) {
        // versor
        double norm = sqrt(dist2);
        dist[0] /= norm;
        dist[1] /= norm;
        dist[2] /= norm;

        int pp, pq;
        for(pp = 0; pp < syst->n_patches; pp++) {
            double p_cos = SCALAR(dist, p->patches[pp]);

            if(p_cos > syst->kf_cosmax) {
                for(pq = 0; pq < syst->n_patches; pq++) {
                    double q_cos = -SCALAR(dist, patches[pq]);
                    if(q_cos > syst->kf_cosmax) {
                        *onp = pp;
                        *onq = pq;
                        return PATCH_BOND;
                    }
                }
            }
        }
    }

    return NO_BOND;
}
// ...
----

== 参考

=== `PatchyParticle` (粒子)の定義

[source, c]
.defs.h
----
// ...
typedef double vector[3];
typedef double matrix[3][3];
// ...
typedef struct PatchyParticle {
    vector r, r_old;
    matrix orientation, orientation_old;
    int index;

    int n_patches;
    vector *patches, *base_patches;

    int cell, cell_old;
} PatchyParticle;
// ...
----

=== `System` の定義

[source, c]
.defs.h
----
// ...
typedef long long int llint;
// ...
typedef struct System {
    int N, N_min, N_max;
    vector box;
    double V;
    double T;
    double z;
    double energy;
    int n_patches;

    /**
     * This matrix is initialised so as to transform base_patches[0] to the 0, 0, 1 vector
     */
    matrix base_orient;
    vector *base_patches;

    int dynamics;
    int ensemble;
    void (*do_dynamics)(struct System *, Output *);
    void (*do_ensemble)(struct System *, Output *);

    llint *SUS_hist;
    llint **SUS_e_hist;
    double SUS_e_step;
    int SUS_e_bins;

    int overlap;

    int tries[N_MOVES];
    int accepted[N_MOVES];

    double disp_max;
    double theta_max;

    double kf_delta, kf_cosmax, kf_sqr_rcut;

    Cells *cells;

    int seed;
    PatchyParticle *particles;
} System;
// ...
----
