= 計算複雑性理論
:description: 計算複雑性理論の用語集

計算複雑性理論の用語集です．


決定問題，判定問題，decision problem::
有限長の入力が与えられ，yesあるいはnoで答える問題．
footnote:wikipedia_decision_problem[https://en.wikipedia.org/wiki/Decision_problem]
* 例) 自然数nが与えられ，それが素数かどうか判定する問題．(素数判定問題)
footnote:wikipedia_decision_problem[]

決定不能問題, undecidable problem::
正しくyesあるいはnoに導くアルゴリズムが構築できないと証明された決定問題．
footnote:wikipedia_undecidable_problem[https://en.wikipedia.org/wiki/Undecidable_problem]
* 例) プログラムの停止性問題
// ** 証明のアプローチ: 任意のプログラムの停止性を判定する機械を設計できたと仮定すると，
// その機械を使って「自分自信が停止すると判定した場合に無限ループを行い，そうでないときに停止する」
// という動作をする機械を設計でき，これは矛盾する．
footnote:wikipedia_undecidable_problem[]

探索問題, 関数問題, function problems::
判定問題の答えが「Yes」である証拠を示す問題
* 探索問題は決定問題に変換可能．
* 例) 充足割り当て問題

最適化問題, optimization problems::
判定問題に関連するある値を最適化する問題
// * 最適化問題は決定問題に変換可能．
// ** 最適化問題である巡回セールスマン問題を例にすると，
// 「コストc以下のハミルトン閉路が存在するか」という決定問題に繰り返し答えていけば，
コストの最小値を求めることができる．
* 一般に，判定問題に付随する最適化問題が解ければ，それに付随する探索問題も解ける
* 最適化問題は探索問題よりも易しくはない

完全問題，complete problems::
決定問題pが決定問題の集合Sに属しており，
かつSに属する任意の問題からpに還元可能なときに，pは完全であると言う．
footnote:wikipedia_decision_problem[]
* Sの完全問題はSの任意の問題よりも簡単ではない．Sの中で最も難しいと考えることができる．
footnote:wikipedia_complete[https://en.wikipedia.org/wiki/Complete_(complexity)]
* 例) 決定問題pがNP問題に属し，かる任意のNP問題からの多項式時間還元が可能な時，pはN完全問題という．
footnote:wikipedia_decision_problem[]

多項式時間アルゴリズム::
時間計算量が多項式オーダであるアルゴリズム
* 例) 行列の掛け算を3重ループで実装した場合，時間計算量は$O(N^3)$となり，これは多項式時間アルゴリズムである．

決定性アルゴリズム::
入力によって動作が一意に定まるアルゴリズム

非決定性アルゴリズム::
入力によって動作が一意に定まらないアルゴリズム
* 答えがYesであるとき，動作の中に少なくとも1つYesと出力する動作が存在する
* 答えがNoであるとき，全ての動作においてNoと出力する

P問題 (P(polynomial)-problem)::
その問題を解く決定性の多項式時間アルゴリズムが存在する判定問題

NP問題 (NP(nondeterministic polynomial)-problem)::
その問題を解く非決定性の多項式時間アルゴリズムが存在する判定問題
* Yesとなる証拠が与えられた時，それを多項式時間で決定的に判定するアルゴリズムが存在する問題．

多項式時間還元，多項式時間変換，多項式時間帰着, polynomial-time reduction::
判定問題Aの判定問題Bへの多項式時間還元とは，
問題Aの入力Iを問題Bの入力I'に多項式時間で変換し，かつ
問題Bの入力I'に対する答えが対応する問題Aにおける入力Iの答えと常に一致することである．

NP困難な問題::
任意のNP問題からの多項式時間還元が存在する問題
* 任意のNP問題から多項式時間還元されるので，任意のNP問題よりも簡単ではない．

NP完全である問題::
NP困難かつNPな問題
* NP完全問題からの多項式時間還元が存在し，NPである問題はNP完全問題
* SAT問題はNP完全であることが初めて証明された問題
** SATからの多項式時間還元が存在することは，任意のNP問題からの多項式時間還元が存在することと同値で，つまりその問題はNP困難である
** NP問題であればNP完全
* NP完全である判定問題は任意のNP問題よりも易しくはない
* P≠NPならば，NP完全である問題を解く多項式アルゴリズムは存在しない
** 仮に多項式時間アルゴリズムで解けるNP完全問題が見つかった場合，P=NPということになり，
その問題に多項式時間還元(他のNP完全問題を経由してもよい)することで任意のNP問題が多項式時間で解けることになる．
* NP問題は軒並みNP完全であることが証明されている
** 例外) 自明なNP問題や，グラフ同型性判定問題(NPであることはわかっている)
* NP - PのうちNP完全ではない問題は存在する． footnote:gokai[http://dopal.cs.uec.ac.jp/okamotoy/PDF/2013/complexity10confusions.pdf]

EXP問題::
その問題を解く決定製の指数関数時間アルゴリズムが存在する判定問題
* 計算可能であるがEXPではない問題は存在する footnote:pnp[https://www.ics.nara-wu.ac.jp/jp/event/koukai/2013/pnp.pdf]
* EXP問題であるがPではない問題は存在する footnote:pnp[]
* EPX問題であるがNP問題ではない問題が存在するかどうかは不明 footnote:pnp[]

