= GNU/Linux


[WARNING]
この記事は2017-06-20現在，執筆中で，未完成です．


== はじめに

GNU/Linuxで自由になる方法が書かれています．コンピュータで，自由にやっていきたいと思っている人の手助けになればと思い，この記事を書いています．

(Windowsや)Macでも自由を得ることは可能ですが，それは小さい自由です．
より大きな自由を得るためにはGNU/Linuxを選択することをお薦めします．

途中，Noteの箇所には「実は」みたいな内容が書かれています．興味のある場合は読んでみてください．


また，以下の長たらしい文章を読みたくないという方のためにlink:/computer/linux_short.html[簡易版]も書いてみました．合わせてご利用ください．
// 基本的には自由ソフトウェア運動に則っていきます．なぜなら，自由ソフトウェアには様々な優位性があるからです．
// しかし，その優位性は自由であることの副産物にすぎません．footnote:[https://www.gnu.org/philosophy/free-software-even-more-important.ja.html]


// [quote, 筆者]
// ____
// 今すぐ窓と全角英数字を捨てて自由になろう!
// ____



== 準備

Macを使っている人はターミナルを使用することで，この章をとばすこと *も* 可能です．

=== GNU/Linuxのインストール

GNU/Linuxといっても様々な種類(ディストリビューション)があり，それぞれインストールの様相が異なります．
ほとんど自動で済んでしまうものもあれば，一からマニュアルで行っていくものもあります
footnote:[一から行うと言っても，インストールの手段が相当丁寧に(日本語で)説明されていますから，それに従えばインストールできます．興味のある人はgentoo wikiやarch wikiを参照してみてください．
この場合，インストール時に自分の選択が反映されるという意味で，より自由であるといえるでしょう．]．

.Linux と GNU/Linux
[NOTE]
GNUという自由ソフトウェア団体が，自由なカーネル(OSの核となる部分)を求めていました．
カーネル以外の基本的なソフトウェアは自由ソフトウェアの思想のもとでほとんどが完成しており，あとカーネルさえ揃えば全て自由なOSが完成する，という段階で，Linux(カーネル)が現れました．
Linuxは，フィンランドのヘルシンキ大学の学生だったLinus Torvaldsによって作られました．これが1991年のことです．
GNUはLinuxを採用し，GNU/Linuxというオペレーティングシステム(OS)として世界に配布します．
ちなみに，現在もLinuxの開発の最終決定権はTorvaldsにあります．
Linuxそのもののソースコードはlink:https://github.com/torvalds/linux[ここ]で見ることができます．

この記事の本題はGNU/Linuxのインストールではないので，(もっとも大事な部分の一つではありますが)簡単に説明するにとどめたいと思います．

// Windowsを使っている人はBash on Windowsを使用することで，この章をとばすこと *も* 可能です．

==== インストール先

普段使っているコンピュータを，ごっそりGNU/Linuxに入れ替えてしまうことが可能です．

WindowsやMacで仮想のコンピュータを起動して，その中にGNU/Linuxをインストールすることもできます．仮想のコンピュータはVirtualBoxやVMwareといったソフトウェアを使用することで簡単に作ることができます．

[NOTE]
普通の人が触れるようなコンピュータであれば，インストール先のコンピュータとして問題ありません．Linuxは様々なコンピュータで動きます．
使わなくなった古いコンピュータに入れても軽快に動く軽量のGNU/Linuxなどもありますので，置物になっている資源を復活させるチャンスです．


==== 手順

インストール先のコンピュータが割と最近のもの(2010年以降くらいなら確実でしょうか)であれば，殆どの以下の手順でインストールできます．
BIOSを操作する点が難しいかもしれませんが，コンピュータに依存する話なので，検索するなどして頑張ってください．

1. ほしいGNU/Linuxディストリビューションのホームページに行く
2. インストールメディアをダウンロードする
3. インストールメディアをUSBメモリにddする(後述)
4. 電源の切れているインストール先のコンピュータにUSBメモリを挿す
5. コンピュータの電源を入れBIOS操作画面に入る
6. USBメモリから起動する
7. あとはインストーラの指示に従う

1から3の手順を自動的に行ってくれるソフトウェア(UNetbootin等)があるようですので，そちらを使っても良いでしょう．慣れてくればddのほうが早くなります．

==== 完成

これで環境は整いましたので，あとは自分の好きな自由ソフトウェアをどんどん追加していってください．自分好みの環境に整えていくのもよいでしょう．
これが可能なのも，自由ソフトウェアのおかげで，一度この自由を手に入れると，後には戻れないでしょう．



== シェル

シェルはLinuxカーネルの上で動くソフトウェアの一つで，シェルを介して他のソフトウェアを実行します．
したがって，Linuxを使うにあたってシェルの操作は(普通の人は)必須です．シェルからすべてが始まると言っても良いでしょう．今後殆どの時間をシェルの上で過ごすことになります．

ターミナルエミュレータ(単にターミナルとも)というソフトウェアを起動すると，同時にシェルが起動され，シェルが利用できるようになります．

.Xとターミナルエミュレータ
[NOTE]
本来はLinuxが起動すると，その後シェル起動します．
しかし，最近のGNU/Linuxでは，起動時にいきなりXと呼ばれるソフトウェアが起動されます．
Xはユーザーに，マウスの使用や，グラフィックの使用を可能にします．
(このような環境は，昔の文字だけの環境(CUI)との対比で，GUIと呼びます．)
X上でGNU/Linuxを扱っている場合には，ターミナルエミュレータというソフトウェアから間接的にシェルを起動する必要があるので，ひと手間かかるのです．
言い換えれば，シェルに一度も触れることなくしてGNU/Linuxを扱うことも可能です．

=== bash

シェルにも色々ありますが，GNU謹製のbashを使うのが普通です．
GNU/Linuxをインストールすると，デフォルトのシェルがbashに設定されているのが普通ですので，あなたが使っているシェルはbashでしょう．
bashでは物足りなくなってきたらzshなどに移行するのもありですが，それでもbashでの知識が今後重要になってきます．

以下bashを使用していると仮定します．

=== プロンプト

今あなたがシェルの前にいると仮定します．何か点滅しているもの(カーソルと言います)が見えると思いますが，あなたはそこにキーボードから文字を打つことができます．
この文字を打つ場所のことをプロンプトと呼びます．
プロンプトに文字を書き，最後にエンターキーを押すことで，打った文字列がシェルに渡されて解釈され(さらにはカーネルに渡されて解釈され(さらにはCPUに渡されて解釈され))処理されます．

=== ファイルとディレクトリ

我々がコンピュータを使うのは，なにかを処理してもらいたからです．
そして，処理したいものの殆どがテキストで表現できます
footnote:[しかもそのテキストは半角英数字や記号を含めても，高々256文字に収まることがほとんどです．この256文字のことをASCIIといいます．]．
したがって，我々の仕事というのはテキスト処理に尽きるのです．

テキストのデータはファイルとして存在しています．
ファイルはどこかに無秩序に置かれているわけではなく，階層構造
footnote:[この構造は木構造であると説明されることがありますが，有向非巡回グラフ(DAG)とするほうが正確です．]
をしたディレクトリという入れ物の中に分類されてまとめられています
どのファイルも例外なく，どこかのディレクトリに入っています．

.テキストとバイナリ
[NOTE]
当然，コンピュータはテキスト以外にも画像などを処理できます．
テキストと画像の違いというのは，実は人間の解釈の違いでしかありません．
コンピュータは，そのファイルがテキストなのか画像なのか判断できません．
したがって，テキストエディタで画像を開けば，画像をテキストと解釈して編集することが可能です
footnote:[普通のテキストエディタであれば，ファイルを開く前にテキストファイルなのかを自動で判別すると思います．その場合は画像をテキストエディタで開くことはできないでしょう．]．
テキストとして解釈するべきでないデータ(たとえば画像など)をバイナリと呼びます．
普通，テキストとバイナリは(実態は同じですが)違う種類のデータとして解釈し，処理を別にします．このファイルがテキストなのかバイナリなのかをコンピュータに伝えることは，処理上大切なことです．

そして，シェルの前に居るあなたは，常にどこかのディレクトリに居ることにもなっています．
今居るディレクトリのことをカレントディレクトリと言います．
ログイン直後(シェルを立ち上げた直後)はホームディレクトリ( `~` と表現されます)という場所にいます．
そこから色々なディレクトリに遷移して，さまざまな作業を行っていくのです．

.どこに何があるのかは誰が決めたの？
[NOTE]
どのディレクトリにどのようなファイルを置くのかというのは，完全に使う人の自由です．
しかし，あまりに自由にしてしまうと，そのコンピュータはその人しか使うことができなくなってしまいます．
ディレクトリの構造に関して，何か共通の認識があったほうが便利な場合が多いです．
そのような取り決めはlink:http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/[Linux Filesystem Hierarchy]にて行われています．
この取り決めの多くは歴史的な経緯に基づいて作成されています(たぶん)．
ただしこれは規格というほどのものではなく，ガイドラインです．
このような取り決めの必要性については，ほぼ自明にわかっていただけると思います．

=== リダイレクトとパイプ

シェルにはリダイレクトとパイプという機能があります．
リダイレクトとパイプというものを知っているか知らないかで，今後の人生が大きく変わります．とてもシンプルですが，画期的な機能です．

==== 標準出力，標準入力

[source, bash]
----
echo 'hello world'
----

たとえば上のコマンドを実行すると，

----
hello world
----

のように， `hello world` が表示されると思います．この `hello world` は `echo` が出力した標準出力と言い, 標準出力はデフォルトでディスプレイに接続されているため，我々の前に表示されます．

この接続先は自由に変えることができます．

例えばファイルに接続すれば，画面に `hello world` が表示される代わりに，その指定したファイルに出力(保存)されることになります．
(リダイレクト)

例えば別のソフトウェアBに繋げれば，標準出力をBの入力に使うことができます．
その入力のことをBの標準入力と言います．
(パイプ)

なお，これらでやり取りされるデータは，全てテキストとして解釈されます．

==== リダイレクト

リダイレクトには2種類あります
footnote:[実際にはもっとありますが，ここでは標準入出力に限ります．]．
ある標準出力をファイルに繋げる `>` と，ファイルをある標準入力に繋げる `<` の2つです．

例えば次の例では `echo` というソフトウェアの標準出力を， `output.txt` というファイルに繋げています．

[source, bash]
----
echo 'hello world' > output.txt
----

上を実行すれば， `output.txt` には `hello world` が出力されているでしょう．

逆に，下の例では，今さっき作成したばかりの `output.txt` の内容を `wc` というソフトウェアの標準入力に繋げています．

[source, bash]
----
wc < output.txt
----

==== パイプ

ある標準出力を，ある標準入力に繋げるものです． `|` 記号を使います．
その名の通り，2つのソフトウェアをパイプで繋げているイメージです．

例えば次の例では `echo` というソフトウェアと `wc` というソフトウェアをパイプでつなげています．
 
[source, bash]
----
echo 'hello world' | wc
----

.標準入出力を用いるソフトウェア
[NOTE]
上の例で登場した `echo` や `wc` といったソフトウェアは，GNU/Linuxに標準で付属しているGNU製のソフトウェアです
footnote:[基本的なテキスト処理を始めとする便利なソフトウェアはGNUにより用意されており，特に, coreutilsと呼ばれている複数のソフトウェアは, GNU/Linuxにまとめて付属されていることがほとんどです．]．
このような標準入出力を用いるプログラムは簡単に作ることができます．
C言語を触ったことがある人は `printf` 関数を知っていると思いますが，その出力は標準出力です． `scanf` は標準入力です．
どんなに簡単な自作のプログラムも，リダイレクトやパイプで即座に他のプログラムやファイルと連携させることができるのです．


// == 追加のソフトウェア
//
// === 入手する
//
// === 自作する


// A footnote footnote:[An example footnote.];
// a second footnote with a reference ID footnoteref:[note2,Second footnote.];
// finally a reference to the second footnote footnoteref:[note2].
//
//
// [quote, GNU, https://www.gnu.org/education/edu-why.ja.html]
// ____
// 学校は、強く、有能で自立した自由な社会の一員となるよう、学生を教育すべきです。
// ____
