= 情報科学


== 定義


=== グラフ
// {{{

ループ loop::
2端点が同一である辺

単純グラフ simple graph::
並列辺もループも含まないグラフ

多重グラフ multigraph::
並列辺やループを含むグラフ

ネットワーク::
各辺に実数の重みがつけられているグラフ

次数 degree::
点vに接続している辺の数をvの次数という
* 任意のグラフの次数の総和は辺数の2倍に等しい
* 任意のグラフの奇点は偶数個存在する
* 全ての点の次数が2以上であるグラフには閉路が存在する

ウォーク walk::
点から始まり点で終わる，点と辺を交互に繰り返す点と辺の系列
* 辺の数は0でもよい

トレイル trail::
全ての辺が異なるウォーク

路 path::
点が全て異なるウォーク
* 路はトレイルである

閉ウォーク closed walk::
端点が等しいウォーク

閉トレイル cosed trail::
全ての辺が異なる閉ウォーク

閉路 cycle::
終点(始点)以外の点が全て異なる長さ(辺の数)が1以上の閉ウォーク
* 閉路は閉トレイルである

連結グラフ connected graph::
任意の2点間に路が存在するグラフ

非連結グラフ disconnected graph::
連結でないグラフ

連結成分 connected component::
極大な連結である部分グラフ

木 tree::
閉路を含まない連結なグラフ
* 木の任意の2点は一意的な路で結ばれている
* 2点以上からなる木には，次数が1の点が2つ以上存在する

森 forest::
閉路を含まないグラフ

独立点集合 independent vertex set::
グラフの点集合の部分集合のうち，任意の2点が隣接していないもの

2部グラフ bipartite graph::
点集合を2つの独立点集合に分割できるグラフ
* グラフが2部グラフであるための必要十分条件は，グラフが奇閉路を含まないこと

オイラートレイル Euler trail::
全ての点と全ての辺を含むトレイル

オイラー閉トレイル Euler losed trail::
全ての点と全ての辺を含む閉トレイル

オイラーグラフ Euler graph::
オイラー閉トレイルが存在するグラフ
* 必要十分条件は，全ての点が偶点
* 一筆書き

完全グラフ complete graph::
全ての異なる2点が辺で結ばれているグラフ

ハミルトン路 Hamilton path::
グラフの全ての点を含む路

ハミルトン閉路 Hamilton cycle::
グラフの全ての点を含む閉路

ハミルトングラフ hamiltonian graph::
ハミルトン閉路の存在するグラフ
* 必要十分条件となる特徴づけは知られていない
* 巡回セールスマン問題を解けば，ハミルトングラフ判定が可能

// }}}

=== アルゴリズム
// {{{

判定問題::
答えが「Yes」あるいは「No」である問題

探索問題::
判定問題の答えが「Yes」である証拠を示す問題

最適化問題::
判定問題に関連するある値を最適化する問題

多項式時間アルゴリズム::
時間計算量が多項式オーダであるアルゴリズム

決定性アルゴリズム::
入力によって動作が一意に定まるアルゴリズム

非決定性アルゴリズム::
入力によって動作が一意に定まらないアルゴリズム
* 答えがYesであるとき，動作の中に少なくとも1つYesと出力する動作が存在する
* 答えがNoであるとき，全ての動作においてNoと出力する

P問題 (P(polynomial)-problem)::
その問題を解く決定性の多項式時間アルゴリズムが存在する判定問題

NP問題 (NP(nondeterministic polynomial)-problem)::
その問題を解く非決定性の多項式時間アルゴリズムが存在する判定問題

NP完全である問題::
NP問題であり，任意のNP問題からの多項式還元が存在する問題
* NP完全である判定問題は任意のNP問題よりも易しくはない
* P≠NPならば，NP完全である問題を解く多項式アルゴリズムは存在しない

NP困難な問題::
付随する判定問題がNP完全である探索問題，あるいは最適化問題
// }}}


== 数値計算

=== 有限差分法

==== 差分形式
// {{{

[latexmath]
++++
f'(x) \simeq \frac{f(x+h) - f(x-h)}{2h} \\
f''(x) \simeq \frac{f(x+h) + f(x-h) - 2f(x)}{h^2}
++++

==== 差分形式の導出

テイラー展開は次の通り．

[latexmath]
++++
f(x) = \sum_{n=0}^{\infty}\frac{f^{(n)}(a)}{n!}(x-a)^n
++++

latexmath:[x-a=h] とすれば，

[latexmath]
++++
f(a+h) = \sum_{n=0}^{\infty}\frac{f^{(n)}(a)}{n!}h^n
++++

となり， latexmath:[a] を latexmath:[x] に戻せば，

[latexmath]
++++
f(x+h) = \sum_{n=0}^{\infty}\frac{f^{(n)}(x)}{n!}h^n
++++

を得る．

これより，次の2つの近似式を得る．

[latexmath]
++++
f(x+h) \simeq f(x) + f'(x)h + \frac{1}{2}f''(x)h^2 \\
f(x-h) \simeq f(x) - f'(x)h + \frac{1}{2}f''(x)h^2
++++

上2式を足したり引いたりすることにより，次の差分形式が得られる．

[latexmath]
++++
f'(x) \simeq \frac{f(x+h) - f(x-h)}{2h} \\
f''(x) \simeq \frac{f(x+h) + f(x-h) - 2f(x)}{h^2}
++++
// }}}
