統計学
======

NUMERICAL RECIPES in C での勉強．

== 用語

モーメント(moment)::
    数値の整数乗の和

ロバスト(robust)な::
    外れ値への依存が少ない，頑健な +
    歪度や尖度といった高次のモーメントはロバストであると言えない．近年はロバスト推定が普及し，重要になってきた．

分散(variance)::
    中心値からの散らばりの度合い． +
    $$`sigma^2 =1/(N-1) sum_(j=1)^N (x_j-bar x)^2`$$
    
歪度(わいど，skewness)::
    $$`1/N sum_(j=1)^N ((x_j-bar x)/sigma)^3`$$ +
    平均値のまわりの分布の非対称さ．無次元量．3次のモーメント．

尖度(せんど，kurtosis)::
    $$`{1/N sum_(j=1)^N ((x_j-bar x)/sigma)^4}-3`$$ +
    正規分布に対して鋭いか平たいか．無次元量．4次のモーメント．-3は正規分布の尖度を0にするため．

標準偏差(standard deviation)::
    分散の平方根

平均(絶対)偏差(average deviation, mean absolute deviation)::
    $$`1/N sum_(j=1)^N |x_j-bar x|`$$ +
    これが標準偏差の代わりに使われないのは，絶対値が解析的でないから．しかし，近年はロバスト推定が普及している．

カイ2乗統計量::
    事象の観測度数を $$`N_i`$$ (整数)，何らかの既知の分布を仮定して導かれる期待度数を $$`n_i`$$ (整数とは限らない)とすると， *カイ2乗統計量* は次式で与えられる． +
    $$`chi^2 = sum_i (N_i - n_i)^2/n_i`$$ +
    $$`n_j = 0`$$となる項は含めない．

不完全ガンマ関数(incomplete gamma function)::
    $$`P(a, x) -= 1/(Gamma(a)) int_0^x e^(-t) t^(a-1) dt`$$

カイ2乗確率関数(chi squared distribution)::
    観測されるカイ2乗の値が $$`chi^2`$$ より小さくなる確率．自由度の個数 $$`nu`$$ は整数． +
    $$`P(chi^2|nu) = P(nu/2, chi^2/2)`$$


== 検定

2つのデータ集合が同じ分布から得られたものと言えるかどうかを判定したい．分布が違うことを示すことができるが，同じであることが証明できるわけではない．離散分布間の差異の検定として， *カイ2乗検定(chi-square test)* がある．(連続分布に関しては *Kolmogorov-Smirnov検定* がある．

// === カイ2乗検定

