= AsciiDoc rendering test
Tetsuro Sakamoto
:toc:

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/

== Paragraphs

Paragraphs don't require special markup in AsciiDoc.
A paragraph is defined by one or more consecutive lines of text.
Line breaks within a paragraph are not displayed.

Leave at least one empty line to begin a new paragraph.

A normal paragraph.

 A literal paragraph.
 One or more consecutive lines indented by at least one space.

 The text is shown in a fixed-width (typically monospace) font.
 The lines are preformatted (i.e., as formatted in the source).
 Spaces and newlines,
 like the ones in this sentence,
 are preserved.

Roses are red, +
violets are blue.

[%hardbreaks]
A ruby is red.
Java is black.

[.lead]
This text will be styled as a lead paragraph (i.e., larger font).

This paragraph will not be.

== Text formatting

It has *strong* significance to me.

I _cannot_ stress this enough.

Type `OK` to accept.

That *_really_* has to go.

Can't pick one? Let's use them `*_all_*`.

**C**reate, **R**ead, **U**pdate, and **D**elete (CRUD)

That's fan__freakin__tastic!

Don't pass generic ``Object``s to methods that accept ``String``s!

It was Beatle**__mania__**!

Werewolves are allergic to #cinnamon#.

##Mark##up refers to text that contains formatting ##mark##s.

Where did all the [.underline]#cores# go?

We need [.line-through]#ten# twenty VMs.

A [.myrole]#custom role# must be fulfilled by the theme.

^super^script phrase

~sub~script phrase

"`double curved quotes`"

'`single curved quotes`'

Olaf's desk was a mess.

A ``std::vector```'s size is the number of items it contains.

All of the werewolves`' desks were a mess.

Olaf had been with the company since the `'00s.

== Section titles

== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title

== Lists

* List item
** Nested list item
*** Nested list item
* List item
 ** Another nested list item
* List item

== Footnotes

A statement.footnote:[Clarification about this statement.]

A bold statement!footnote:disclaimer[Opinions are my own.]

Another bold statement.footnote:disclaimer[]

== Literals and source code

.Some Ruby code
[source,ruby]
----
require 'sinatra'

get '/hi' do
  "Hello World!"
end
----


== Old tests

asciidoc source from link:http://asciidoc.org/[asciidoc.org]

* 1111111111
* 1111111111
** 2222222222
** 2222222222
* 1111111111
* 1111111111
** 2222222222
** 2222222222
** 2222222222
*** 3333333333
*** 3333333333
*** 3333333333
*** 3333333333
** 2222222222
** 2222222222

== Macros

=== image_grid

image_grid::begin[]

.image_cell_1
image_cell::/images/plant/2019-08-27/p8273777[]
.image_cell_2
image_cell::/images/plant/2019-08-27/p8273778[]


image_grid::end[]

== class attributes

hoge hoge [.hoge]#hoge hoge#.


== List continuation

* The header in AsciiDoc must start with a document title.
+
----
= Document Title
----
+
Keep in mind that the header is optional.

* Optional Author and Revision information immediately follows the header title.
+
----
= Document Title
Doc Writer <doc.writer@asciidoc.org>
v1.0, 2013-01-01
----


== CSS 

== h2

=== h3
 
==== h4


== Math Formulae

=== LaTeXMathML (MathJax)

http://www.maths.nottingham.ac.uk/personal/drw/lm.html[LaTeXMathML]
capability has been added to AsciiDoc for users who are more familar
with or prefer LaTeX math formulas to the
http://asciidoc.org/asciimathml.html[ASCIIMathML]
notation.

'LaTeXMathML' is a derivative of
http://asciidoc.org/asciimathml.html[ASCIIMathML] -- in
terms of usage the only difference it that you use the `latexmath`
attribute instead of the `asciimath` attribute.

'LaTeXMathML' processes LaTeX math formulas not arbitrary LaTeX (as
`dblatex(1)` does). See the
http://www.maths.nottingham.ac.uk/personal/drw/lm.html[LaTeXMathML]
website for details.

Here's the link:latexmathml.txt[AsciiDoc source] that generated this
page.

Some example 'LaTeXMathML' formulas:


[latexmath]
++++
R_x = 10.0 \times \sin(R_\phi)
++++



== Syntax Highlighting

=== Source code paragraphs

[source,python]
if n < 0: print 'Hello World!'

:language: python

[source]
if n < 0: print 'Hello World!'

[source,ruby,numbered]
[true, false].cycle([0, 1, 2, 3, 4]) do |a, b|
    puts "#{a.inspect} => #{b.inspect}"


=== Unnumbered source code listing

[source,python]
---------------------------------------------------------------------
''' A multi-line
    comment.'''
def sub_word(mo):
    ''' Single line comment.'''
    word = mo.group('word')   # Inline comment
    if word in keywords[language]:
        return quote + word + quote
    else:
        return word
---------------------------------------------------------------------

comment def sub_word

word mo.group() if word in keywords

本日は晴天なり．


=== Numbered source code listing with callouts

[source,ruby,numbered]
---------------------------------------------------------------------
#
# Useful Ruby base class extensions.
#

class Array

  # Execute a block passing it corresponding items in
  # +self+ and +other_array+.
  # If self has less items than other_array it is repeated.

  def cycle(other_array)  # :yields: item, other_item
    other_array.each_with_index do |item, index|
      yield(self[index % self.length], item)
    end
  end

end

if $0 == __FILE__                                 # <1>
  # Array#cycle test
  # true => 0
  # false => 1
  # true => 2
  # false => 3
  # true => 4
  puts 'Array#cycle test'                         # <2>
  [true, false].cycle([0, 1, 2, 3, 4]) do |a, b|
    puts "#{a.inspect} => #{b.inspect}"
  end
end
---------------------------------------------------------------------

<1> First callout.
<2> Second callout.
